import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Toaster } from "@/components/ui/toaster";
import MaxWidthWrapper from "@/components/Wrapper";
import Navbar from "@/components/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          "flex flex-col h-screen min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <MaxWidthWrapper>
          <Navbar />
          {children}
          <Toaster />
        </MaxWidthWrapper>
      </body>
    </html>
  );
}
